const fs = require('fs');

const improvedHi = {
  "Home": "होम",
  "Stationery": "स्टेशनरी",
  "Printing Services": "प्रिंटिंग सेवाएँ",
  "Xerox": "ज़ेरॉक्स",
  "Lamination": "लैमिनेशन",
  "Binding": "बाइंडिंग",
  "Passport Photos": "पासपोर्ट फोटो",
  "Pricing": "कीमतें",
  "Gallery": "गैलरी",
  "Contact": "संपर्क",
  "Need urgent prints today? Share files on WhatsApp and get a quick quote in minutes.": "क्या आज तत्काल प्रिंट की आवश्यकता है? WhatsApp पर फाइलें भेजें और मिनटों में कीमत का अनुमान प्राप्त करें।",
  "WhatsApp Quote": "WhatsApp पर कीमत जानें",
  "Call Shop": "दुकान पर कॉल करें",
  "VIRAR'S TRUSTED STATIONERY, PRINTING & XEROX DESTINATION": "विरार का सबसे भरोसेमंद स्टेशनरी, प्रिंटिंग और ज़ेरॉक्स डेस्टिनेशन",
  "Your One-Stop Shop for": "आपकी सभी ज़रूरतों के लिए एक ही जगह:",
  "Printing": "प्रिंटिंग",
  "in Virar": "विरार में",
  "Serving students, offices and local businesses with fast Xerox, colour printing, lamination, binding, passport photos and stationery essentials.": "छात्रों, कार्यालयों और स्थानीय व्यवसायों को तेज़ ज़ेरॉक्स, कलर प्रिंटिंग, लैमिनेशन, बाइंडिंग, पासपोर्ट फोटो और आवश्यक स्टेशनरी प्रदान कर रहे हैं।",
  "Fast prints. Reliable service.": "तेज़ प्रिंटिंग। भरोसेमंद सेवा।",
  "Send Files on WhatsApp": "WhatsApp पर फाइलें भेजें",
  "Call Now": "अभी कॉल करें",
  "10+ Years Serving Virar": "10+ वर्षों से विरार की सेवा में",
  "2,00,000+ Happy Customers": "2,00,000+ संतुष्ट ग्राहक",
  "Same-Day Delivery Available": "उसी दिन डिलीवरी उपलब्ध",
  "Open 7 Days · 8am - 9pm": "7 दिन खुला · सुबह 8 से रात 9 बजे",
  "Bulk Orders Accepted": "थोक ऑर्डर स्वीकार किए जाते हैं",
  "For offices, schools and projects": "कार्यालयों, स्कूलों और प्रोजेक्ट्स के लिए",
  "Passport Photos in 10 Minutes": "10 मिनट में पासपोर्ट फोटो",
  "Quick photo print service": "त्वरित फोटो प्रिंट सेवा",
  "Print Documents": "दस्तावेज़ प्रिंट करें",
  "Fast print support for forms and files.": "फॉर्म और फाइलों के लिए त्वरित प्रिंट सपोर्ट।",
  "WhatsApp Inquiry": "WhatsApp द्वारा पूछताछ",
  "Send files and questions instantly.": "फाइलें और प्रश्न तुरंत भेजें।",
  "Talk directly for urgent orders.": "तत्काल ऑर्डर के लिए सीधे बात करें।",
  "Get Directions": "रास्ता देखें",
  "Find the exact shop location quickly.": "दुकान का सटीक स्थान आसानी से खोजें।",
  "View Services": "सेवाएँ देखें",
  "See all available printing options.": "सभी उपलब्ध प्रिंटिंग विकल्प देखें।",
  "Ask for Prices": "कीमतें पूछें",
  "Check starting rates before visiting.": "आने से पहले शुरुआती दरें चेक करें।",
  "Popular Services": "लोकप्रिय सेवाएँ",
  "Most requested services with starting prices": "शुरुआती कीमतों के साथ सबसे अधिक मांगी जाने वाली सेवाएँ",
  "Indicative prices to help customers estimate costs quickly.": "ग्राहकों को लागत का अनुमान लगाने में मदद करने के लिए सांकेतिक कीमतें।",
  "Most Popular": "सबसे लोकप्रिय",
  "Xerox / Photocopy": "ज़ेरॉक्स / फोटोकॉपी",
  "Starting from": "शुरुआती कीमत",
  "Colour Printout": "कलर प्रिंटआउट",
  "Spiral Binding": "स्पाइरल बाइंडिंग",
  "Smart Card": "स्मार्ट कार्ड",
  "Instant Quote": "तत्काल अनुमान",
  "Calculate your print estimate in seconds": "सेकंडों में अपने प्रिंट का अनुमानित खर्च जानें",
  "Get a quick price estimate before you WhatsApp your files. Final pricing is confirmed at the shop.": "फ़ाइलें WhatsApp करने से पहले त्वरित कीमत अनुमान प्राप्त करें। अंतिम कीमत की पुष्टि दुकान पर की जाएगी।",
  "Select a service": "कोई सेवा चुनें",
  "Pick the service you want to estimate.": "वह सेवा चुनें जिसका आप अनुमान चाहते हैं।",
  "Service Type": "सेवा का प्रकार",
  "Select service": "सेवा चुनें",
  "Black &amp; White Printing": "ब्लैक एंड व्हाइट प्रिंटिंग",
  "Color Printing": "कलर प्रिंटिंग",
  "Jumbo Xerox": "जंबो ज़ेरॉक्स",
  "Choose options": "विकल्प चुनें",
  "Size, color, and quantity help us estimate accurately.": "आकार, रंग और मात्रा हमें सटीक अनुमान लगाने में मदद करते हैं।",
  "Paper Size": "कागज का आकार",
  "Standard": "मानक (Standard)",
  "Print Type": "प्रिंट का प्रकार",
  "Black &amp; White": "ब्लैक एंड व्हाइट",
  "Color": "रंग",
  "Quantity": "मात्रा",
  "Add finishing services": "फिनिशिंग सेवाएँ जोड़ें",
  "Optional add-ons that improve presentation and durability.": "वैकल्पिक सेवाएँ जो प्रस्तुति और टिकाऊपन में सुधार करती हैं।",
  "Estimates update instantly. Final pricing depends on paper choice and file details.": "अनुमान तुरंत अपडेट होते हैं। अंतिम कीमत कागज के चुनाव और फ़ाइल विवरण पर निर्भर करती है।",
  "Upload PDF": "PDF अपलोड करें",
  "(Optional)": "(वैकल्पिक)",
  "Drop your PDF and we'll count the pages automatically.": "अपना PDF यहाँ छोड़ें और हम अपने आप पृष्ठ गिन लेंगे।",
  "Drop PDF here or": "PDF यहाँ छोड़ें या",
  "browse": "ब्राउज़ करें",
  "Page count auto-fills quantity · Max 25 MB": "पृष्ठों की गिनती अपने आप मात्रा भर देगी · अधिकतम 25 MB",
  "Your Estimate": "आपका अनुमान",
  "Live pricing": "लाइव कीमतें",
  "Per Unit": "प्रति इकाई",
  "Total Cost": "कुल लागत",
  "Select a service to calculate pricing.": "कीमत की गणना करने के लिए एक सेवा चुनें।",
  "Send Quote on WhatsApp": "WhatsApp पर अनुमान भेजें",
  "All estimates are indicative and confirmed after file review.": "सभी अनुमान सांकेतिक हैं और फ़ाइल देखने के बाद ही पक्के किए जाएँगे।",
  "Downloads": "डाउनलोड",
  "Quick PDF guides for pricing and services": "कीमतों और सेवाओं के लिए त्वरित PDF गाइड",
  "Download the latest price list and service guide to plan your visit or office order.": "अपनी यात्रा या कार्यालय आदेश की योजना बनाने के लिए नवीनतम मूल्य सूची और सेवा गाइड डाउनलोड करें।",
  "Price List PDF": "मूल्य सूची PDF",
  "Updated pricing overview for popular printing and xerox services.": "लोकप्रिय प्रिंटिंग और ज़ेरॉक्स सेवाओं के लिए अद्यतन मूल्य सूची।",
  "Download Price List": "मूल्य सूची डाउनलोड करें",
  "Service Guide PDF": "सेवा गाइड PDF",
  "Service details, turnaround times, and ordering tips in one file.": "सेवा विवरण, समय और ऑर्डर करने के सुझाव एक ही फ़ाइल में।",
  "Download Service Guide": "सेवा गाइड डाउनलोड करें",
  "How It Works": "यह कैसे काम करता है",
  "Simple 3-step process for faster service": "तेज़ सेवा के लिए सरल 3-चरणीय प्रक्रिया",
  "From WhatsApp file sharing to easy pickup at the shop.": "WhatsApp पर फ़ाइल साझा करने से लेकर दुकान पर आसान पिकअप तक।",
  "Send your file on WhatsApp": "अपनी फ़ाइल WhatsApp पर भेजें",
  "Share documents, images, or print instructions directly.": "दस्तावेज़, चित्र या प्रिंट निर्देश सीधे साझा करें।",
  "Confirm print details and quantity": "प्रिंट विवरण और मात्रा की पुष्टि करें",
  "Approve paper, copies, size, and final cost quickly.": "कागज, प्रतियाँ, आकार और अंतिम कीमत जल्दी से स्वीकृत करें।",
  "Visit the shop and collect your order": "दुकान पर आएँ और अपना ऑर्डर लें",
  "Pickup at Virar Stationery & Jumbo Xerox with ease.": "विरार स्टेशनरी और जंबो ज़ेरॉक्स पर आसानी से पिकअप करें।",
  "Printing, Xerox & Stationery Services": "प्रिंटिंग, ज़ेरॉक्स और स्टेशनरी सेवाएँ",
  "Fast, Reliable & Affordable Services for Students, Offices and Everyday Needs": "छात्रों, कार्यालयों और रोज़मर्रा की ज़रूरतों के लिए तेज़, विश्वसनीय और किफायती सेवाएँ",
  "From colour printouts and xerox to lamination, binding and stationery, we provide everything you need under one roof in Virar.": "कलर प्रिंटआउट और ज़ेरॉक्स से लेकर लैमिनेशन, बाइंडिंग और स्टेशनरी तक, हम विरार में एक ही छत के नीचे आपकी ज़रूरत की हर चीज़ प्रदान करते हैं।",
  "Black & White Printing": "ब्लैक एंड व्हाइट प्रिंटिंग",
  "Sharp monochrome prints for forms, assignments, reports and office documents.": "फॉर्म, असाइनमेंट, रिपोर्ट और कार्यालय दस्तावेजों के लिए स्पष्ट ब्लैक एंड व्हाइट प्रिंट्स।",
  "Learn More": "और जानें",
  "Vibrant colour prints for presentations, brochures, posters and project work.": "प्रेजेंटेशन, ब्रोशर, पोस्टर और प्रोजेक्ट वर्क के लिए शानदार कलर प्रिंट्स।",
  "Affordable photocopying for books, forms, IDs and daily office needs.": "किताबों, फॉर्मों, आईडी और दैनिक कार्यालय की ज़रूरतों के लिए किफायती फोटोकॉपी।",
  "Protect important certificates, ID cards and documents with durable lamination.": "महत्वपूर्ण प्रमाणपत्रों, आईडी कार्ड और दस्तावेजों को टिकाऊ लैमिनेशन से सुरक्षित करें।",
  "Professional binding for project reports, files and presentations.": "प्रोजेक्ट रिपोर्ट, फाइलें और प्रेजेंटेशन के लिए पेशेवर बाइंडिंग।",
  "Quick passport-size photo prints with clean framing and fast delivery.": "साफ फ्रेमिंग और तेज़ डिलीवरी के साथ त्वरित पासपोर्ट-साकार फोटो प्रिंट्स।",
  "Project Printing": "प्रोजेक्ट प्रिंटिंग",
  "Complete support for school and college projects with print and finishing options.": "प्रिंट और फिनिशिंग विकल्पों के साथ स्कूल और कॉलेज परियोजनाओं के लिए पूर्ण समर्थन।",
  "Stationery Products": "स्टेशनरी उत्पाद",
  "Daily-use stationery, notebooks, pens, files, and office essentials in one place.": "दैनिक उपयोग की स्टेशनरी, नोटबुक, पेन, फाइलें और कार्यालय की आवश्यक वस्तुएँ एक ही स्थान पर।",
  "Blackbook Printing": "ब्लैकबुक प्रिंटिंग",
  "Clear and durable blackbook print service for projects, records, and submissions.": "प्रोजेक्ट्स, रिकॉर्ड और सबमिशन के लिए स्पष्ट और टिकाऊ ब्लैकबुक प्रिंट सेवा।",
  "Letterhead Print": "लेटरहेड प्रिंट",
  "Professional letterhead printing for offices, shops, and local business branding.": "कार्यालयों, दुकानों और स्थानीय व्यापार ब्रांडिंग के लिए पेशेवर लेटरहेड प्रिंटिंग।",
  "Visiting Card": "विज़िटिंग कार्ड",
  "Neat visiting card printing with quality finish for personal and business use.": "व्यक्तिगत और व्यावसायिक उपयोग के लिए गुणवत्तापूर्ण फिनिश के साथ बेहतरीन विज़िटिंग कार्ड प्रिंटिंग।",
  "Billbook Print": "बिल्बुक प्रिंट",
  "Custom billbook printing for daily billing, invoicing, and store operations.": "दैनिक बिलिंग, चालान और स्टोर संचालन के लिए कस्टम बिलबुक प्रिंटिंग।",
  "Smart card printing for ID cards, membership cards, office cards and custom cards. Starting from &#8377;80.": "आईडी कार्ड, सदस्यता कार्ड, कार्यालय कार्ड और कस्टम कार्ड के लिए स्मार्ट कार्ड प्रिंटिंग। ₹80 से शुरू।",
  "Large-size xerox and copy solutions available in A3, A2, A1, A0, A00 for drawings, plans, posters, and charts.": "चित्र, योजना, पोस्टर और चार्ट के लिए A3, A2, A1, A0, A00 आकार में बड़े ज़ेरॉक्स और कॉपी समाधान उपलब्ध हैं।",
  "Cartridge Refilling": "कार्ट्रिज रिफिलिंग",
  "Reliable ink and toner cartridge refilling for regular office and home printing.": "नियमित कार्यालय और घरेलू प्रिंटिंग के लिए विश्वसनीय स्याही और टोनर कार्ट्रिज रिफिलिंग।",
  "All Size Scanning": "सभी आकारों की स्कैनिंग",
  "Document scanning support in multiple sizes for records, forms, and submissions.": "रिकॉर्ड, फॉर्म और सबमिशन के लिए कई आकारों में दस्तावेज़ स्कैनिंग समर्थन।",
  "Computer Accessories": "कंप्यूटर एक्सेसरीज़",
  "Essential computer accessories including cables, peripherals, and daily-use items.": "केबल, पेरिफेरल और दैनिक उपयोग की वस्तुओं सहित आवश्यक कंप्यूटर एक्सेसरीज़।",
  "Why Choose Us": "हमें क्यों चुनें",
  "Why Virar Chooses Us": "विरार हमें क्यों चुनता है",
  "Fast service, affordable pricing, professional quality, and trusted support for students, offices, and families across Virar.": "विरार भर में छात्रों, कार्यालयों और परिवारों के लिए तेज़ सेवा, किफायती मूल्य, पेशेवर गुणवत्ता और विश्वसनीय समर्थन।",
  "Fast Turnaround": "तेज़ सेवा",
  "Urgent printouts, xerox, lamination, and project work completed quickly with same-day service available.": "तत्काल प्रिंटआउट, ज़ेरॉक्स, लैमिनेशन और प्रोजेक्ट कार्य जल्दी पूरा किया जाता है, उसी दिन की सेवा उपलब्ध है।",
  "Most Chosen": "सबसे अधिक चुना गया",
  "Affordable Pricing": "किफायती मूल्य",
  "Budget-friendly rates for students, offices, bulk orders, and everyday printing needs.": "छात्रों, कार्यालयों, थोक ऑर्डर और रोज़मर्रा की प्रिंटिंग आवश्यकताओं के लिए बजट के अनुकूल दरें।",
  "Professional Quality": "पेशेवर गुणवत्ता",
  "Sharp printing, neat finishing, accurate colours, and premium-quality materials for every order.": "हर ऑर्डर के लिए स्पष्ट प्रिंटिंग, साफ फिनिशिंग, सटीक रंग और प्रीमियम-गुणवत्ता वाली सामग्री।",
  "Trusted Local Support": "विश्वसनीय स्थानीय समर्थन",
  "Friendly assistance, WhatsApp ordering, quick guidance, and reliable service trusted across Virar.": "मैत्रीपूर्ण सहायता, WhatsApp ऑर्डरिंग, त्वरित मार्गदर्शन और पूरे विरार में विश्वसनीय सेवा।",
  "10+ Years in Virar": "विरार में 10+ वर्ष",
  "200,000+ Customers Served Since 2016": "2016 से 200,000+ ग्राहकों की सेवा की गई",
  "Same-Day Service": "उसी दिन सेवा",
  "Open 7 Days a Week": "सप्ताह के 7 दिन खुला",
  "Featured Products": "विशेष उत्पाद",
  "Stationery essentials for school, college, and office use": "स्कूल, कॉलेज और कार्यालय उपयोग के लिए आवश्यक स्टेशनरी",
  "Quality stationery essentials for students, offices, and businesses — available at our shop.": "छात्रों, कार्यालयों और व्यवसायों के लिए उच्च गुणवत्ता वाली आवश्यक स्टेशनरी - हमारी दुकान पर उपलब्ध।",
  "Pens": "पेन",
  "Reliable writing tools for everyday use.": "रोज़मर्रा के उपयोग के लिए भरोसेमंद लेखन सामग्री।",
  "Notebooks": "नोटबुक",
  "Durable notebooks for study and office notes.": "अध्ययन और कार्यालय नोट्स के लिए टिकाऊ नोटबुक।",
  "Files": "फ़ाइलें",
  "Keep documents sorted and ready to present.": "दस्तावेजों को व्यवस्थित और प्रस्तुति के लिए तैयार रखें।",
  "Art Supplies": "कला सामग्री",
  "Materials for creative school and hobby work.": "रचनात्मक स्कूल और शौक के कार्यों के लिए सामग्री।",
  "Calculators": "कैलकुलेटर",
  "Useful calculators for class and work tasks.": "कक्षा और काम के कार्यों के लिए उपयोगी कैलकुलेटर।",
  "Charts": "चार्ट",
  "Classroom and project charts that stand out.": "कक्षा और प्रोजेक्ट चार्ट जो अलग दिखते हैं।",
  "Project Materials": "प्रोजेक्ट सामग्री",
  "All the pieces needed for neat project work.": "बेहतरीन प्रोजेक्ट कार्य के लिए आवश्यक सभी सामग्री।",
  "Sticky Notes": "स्टिकी नोट्स",
  "Handy notes for reminders and योजना.": "रिमाइंडर और योजना के लिए उपयोगी नोट्स।",
  "Inside the Shop": "दुकान के अंदर",
  "A quick look at our daily work, printing setup, stationery shelves, and customer service.": "हमारे दैनिक कार्य, प्रिंटिंग सेटअप, स्टेशनरी शेल्फ और ग्राहक सेवा की एक झलक।",
  "What customers say": "ग्राहक क्या कहते हैं",
  "What our customers say about their experience.": "हमारे ग्राहक अपने अनुभव के बारे में क्या कहते हैं।",
  "I needed 80 pages of my final year project printed and spiral bound urgently. They finished it in under 30 minutes — print quality was sharp and the binding looked professional. I've been coming here since first year and they never disappoint.": "मुझे अपने अंतिम वर्ष के प्रोजेक्ट के 80 पृष्ठों को तत्काल प्रिंट और स्पाइरल बाउंड कराने की आवश्यकता थी। उन्होंने इसे 30 मिनट से भी कम समय में पूरा कर दिया — प्रिंट की गुणवत्ता स्पष्ट थी और बाइंडिंग पेशेवर लग रही थी। मैं प्रथम वर्ष से यहाँ आ रहा हूँ और वे कभी निराश नहीं करते।",
  "Engineering Student, Viva College": "इंजीनियरिंग छात्र, विवा कॉलेज",
  "Thesis Printing & Binding": "थीसिस प्रिंटिंग और बाइंडिंग",
  "We get our office letterheads, visiting cards, and daily xerox done here. The uncle and his team are very reliable — pricing is always fair and they remember our preferences. Best print shop in Virar West, hands down.": "हम अपने कार्यालय के लेटरहेड, विज़िटिंग कार्ड और दैनिक ज़ेरॉक्स यहीं से करवाते हैं। अंकल और उनकी टीम बहुत विश्वसनीय है — कीमतें हमेशा उचित होती हैं और उन्हें हमारी पसंद याद रहती है। विरार वेस्ट में सबसे अच्छी प्रिंट शॉप।",
  "Office Manager, Local Business": "कार्यालय प्रबंधक, स्थानीय व्यवसाय",
  "Name": "नाम",
  "Phone Number": "फ़ोन नंबर",
  "Email (Optional)": "ईमेल (वैकल्पिक)",
  "Business / Institution (Optional)": "व्यवसाय / संस्थान (वैकल्पिक)",
  "Service Required": "आवश्यक सेवा",
  "Expected Quantity": "अपेक्षित मात्रा",
  "Project Description / Special Requests": "प्रोजेक्ट विवरण / विशेष अनुरोध",
  "Send Enquiry via WhatsApp": "WhatsApp के माध्यम से पूछताछ भेजें",
  "Our Location": "हमारा स्थान",
  "Old Viva College Rd, Virar West, Virar, Maharashtra 401303": "ओल्ड विवा कॉलेज रोड, विरार वेस्ट, विरार, महाराष्ट्र 401303",
  "Business Hours": "कार्य के घंटे",
  "Monday - Sunday": "सोमवार - रविवार",
  "8:00 AM - 9:00 PM": "सुबह 8:00 - रात 9:00",
  "Quick Links": "महत्वपूर्ण लिंक",
  "All Rights Reserved.": "सर्वाधिकार सुरक्षित।",
  "Order Tracking Status": "ऑर्डर ट्रैकिंग स्थिति"
};

let js = fs.readFileSync('assets/js/features/language-toggle.js', 'utf8');
let lines = js.split('\n');

let hiIdx = lines.findIndex(l => l.includes('  hi: {'));
let inHiBlock = false;
let replacementsCount = 0;

for (let i = hiIdx; i < lines.length; i++) {
  if (lines[i].includes('  hi: {')) {
    inHiBlock = true;
    continue;
  }
  
  if (inHiBlock && lines[i].startsWith('  },')) {
    inHiBlock = false;
    break;
  }

  if (inHiBlock) {
    let line = lines[i];
    let match = line.match(/^\s*'([^']+)'\s*:/);
    if (!match) match = line.match(/^\s*"([^"]+)"\s*:/);
    
    if (match) {
      let key = match[1];
      let unescapedKey = key.replace(/\\'/g, "'");
      
      if (improvedHi[unescapedKey]) {
        let safeVal = improvedHi[unescapedKey].replace(/'/g, "\\'");
        lines[i] = line.replace(/(:\s*').*?(',?)$/, `$1${safeVal}$2`);
        replacementsCount++;
      }
    }
  }
}

fs.writeFileSync('assets/js/features/language-toggle.js', lines.join('\n'));
console.log('Replacements made in hi block: ' + replacementsCount);
