#!/usr/bin/env node
/**
 * build-sitemap.js — XML Sitemap Generator
 *
 * Scans the repository for canonical, indexable .html pages and
 * regenerates sitemap.xml at the repo root. This is a build artifact:
 * the script is the source of truth, sitemap.xml is generated output.
 * CI re-runs this on every push so the sitemap never drifts from the
 * actual page set (and picks up newly-added areas/*.html landing pages
 * automatically).
 *
 * What gets included (and its priority):
 *   - index.html ............................ 1.0  (root, trailing-slash URL)
 *   - services/*.html ....................... 0.9  (core service pages)
 *   - areas/*.html (only if folder exists) .. 0.8  (local landing pages)
 *   - pages/pricing.html .................... 0.8
 *   - pages/review.html ..................... 0.5  (public, canonical)
 *   - pages/sitemap.html .................... 0.4  (human-readable index)
 *   - pages/privacy.html .................... 0.3
 *   - pages/terms.html ...................... 0.3
 *
 * Explicitly excluded: _partials/, node_modules/, scripts/, docs/,
 * review/ (the embeddable widget dir — not a canonical page), and any
 * non-HTML asset.
 *
 * Usage:   npm run build:sitemap   (or: node scripts/build-sitemap.js)
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(ROOT, 'sitemap.xml');

const BASE = 'https://virarprint.in/';
const CHANGEFREQ = 'weekly';

// lastmod for every URL = the build date (YYYY-MM-DD).
const LASTMOD = new Date().toISOString().slice(0, 10);

/**
 * Priority lookup for explicitly-known pages, keyed by repo-relative path.
 * Pages discovered by directory scan (services/, areas/) fall back to the
 * DIR_PRIORITY map below.
 */
const PAGE_PRIORITY = {
  'index.html': '1.0',
  'pages/pricing.html': '0.8',
  'pages/review.html': '0.5',
  'pages/sitemap.html': '0.4',
  'pages/privacy.html': '0.3',
  'pages/terms.html': '0.3',
};

// Default priority for every .html found inside these scanned directories.
const DIR_PRIORITY = {
  services: '0.9',
  areas: '0.8',
};

/**
 * Convert a repo-relative path to its canonical public URL.
 * index.html maps to the trailing-slash root ("/"), everything else
 * keeps its path verbatim.
 */
function toLoc(relPath) {
  if (relPath === 'index.html') return BASE;
  return BASE + relPath.split(path.sep).join('/');
}

/** Return sorted *.html filenames in a repo subdir, or [] if it's absent. */
function listHtml(dir) {
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs) || !fs.statSync(abs).isDirectory()) return [];
  return fs
    .readdirSync(abs)
    .filter((f) => f.toLowerCase().endsWith('.html'))
    .sort();
}

// --- Collect the page set in deliberate (priority-descending) order ---
const entries = [];

// 1. Root
entries.push({ loc: toLoc('index.html'), priority: PAGE_PRIORITY['index.html'] });

// 2. services/*.html — every page in the folder, scanned dynamically
for (const file of listHtml('services')) {
  const rel = path.join('services', file);
  entries.push({ loc: toLoc(rel), priority: DIR_PRIORITY.services });
}

// 3. areas/*.html — ONLY if the folder exists (generated by another agent)
const areaFiles = listHtml('areas');
if (areaFiles.length) {
  for (const file of areaFiles) {
    const rel = path.join('areas', file);
    entries.push({ loc: toLoc(rel), priority: DIR_PRIORITY.areas });
  }
}

// 4. Known pages/*.html, in priority order, only if present on disk
const KNOWN_PAGES = [
  'pages/pricing.html',
  'pages/review.html',
  'pages/sitemap.html',
  'pages/privacy.html',
  'pages/terms.html',
];
for (const rel of KNOWN_PAGES) {
  if (fs.existsSync(path.join(ROOT, rel))) {
    entries.push({ loc: toLoc(rel), priority: PAGE_PRIORITY[rel] });
  } else {
    console.warn(`  ⚠ skipped (not found): ${rel}`);
  }
}

// --- Render pretty-printed, valid XML ---
const lines = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
];

for (const { loc, priority } of entries) {
  lines.push('  <url>');
  lines.push(`    <loc>${loc}</loc>`);
  lines.push(`    <lastmod>${LASTMOD}</lastmod>`);
  lines.push(`    <changefreq>${CHANGEFREQ}</changefreq>`);
  lines.push(`    <priority>${priority}</priority>`);
  lines.push('  </url>');
}

lines.push('</urlset>');
lines.push('');

const xml = lines.join('\n');
fs.writeFileSync(OUTPUT, xml, 'utf8');

// --- Summary log ---
console.log('🗺  Sitemap generated:');
for (const { loc, priority } of entries) {
  console.log(`   [${priority}] ${loc}`);
}
console.log(`\n✅ Wrote ${path.relative(ROOT, OUTPUT)} — ${entries.length} URLs (lastmod ${LASTMOD}).`);
if (!areaFiles.length) {
  console.log('   ℹ areas/ not present — skipped (will be picked up once it exists).');
}
