#!/usr/bin/env node
/**
 * build-css.js — CSS Bundle Builder
 *
 * Reads assets/css/main.css, resolves each @import in cascade order,
 * concatenates all 22 module files into a single bundle.
 *
 * Usage:
 *   node scripts/build-css.js
 *
 * Output:
 *   assets/css/main.bundled.css
 *
 * The modular source files are NOT modified — they remain the source of truth.
 * The bundled file is a build artifact for production use.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const MANIFEST = path.join(ROOT, 'assets', 'css', 'main.css');
const OUTPUT = path.join(ROOT, 'assets', 'css', 'main.bundled.css');

// Read the manifest
const manifestContent = fs.readFileSync(MANIFEST, 'utf8');

// Extract @import paths in order
const importRegex = /@import\s+url\(['"]?([^'")]+)['"]?\);?/g;
const imports = [];
let match;

while ((match = importRegex.exec(manifestContent)) !== null) {
  imports.push(match[1]);
}

if (imports.length === 0) {
  console.error('Error: No @import statements found in main.css');
  process.exit(1);
}

console.log(`Found ${imports.length} @import statements in main.css\n`);

// Build the bundle
const timestamp = new Date().toISOString().replace('T', ' ').split('.')[0];
const parts = [
  `/* ================================================================`,
  `   main.bundled.css — Auto-generated from main.css @import manifest`,
  `   Generated: ${timestamp}`,
  `   Source files: ${imports.length}`,
  ``,
  `   DO NOT EDIT THIS FILE DIRECTLY.`,
  `   Edit the individual module files under assets/css/ instead,`,
  `   then re-run: node scripts/build-css.js`,
  `   ================================================================ */`,
  ``
];

let totalLines = 0;
let totalBytes = 0;

for (const importPath of imports) {
  // Resolve relative to the css directory
  const filePath = path.resolve(path.dirname(MANIFEST), importPath);
  const relativePath = path.relative(ROOT, filePath);

  if (!fs.existsSync(filePath)) {
    console.error(`  ✗ MISSING: ${relativePath}`);
    process.exit(1);
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const lineCount = content.split('\n').length;
  totalLines += lineCount;
  totalBytes += Buffer.byteLength(content, 'utf8');

  parts.push(`/* --- ${relativePath} --- */`);
  parts.push(content.trim());
  parts.push(''); // blank line between modules

  console.log(`  ✓ ${relativePath} (${lineCount} lines)`);
}

const bundle = parts.join('\n');
fs.writeFileSync(OUTPUT, bundle, 'utf8');

const bundleSize = Buffer.byteLength(bundle, 'utf8');
const bundleSizeKB = (bundleSize / 1024).toFixed(1);

console.log(`\n✅ Bundle written to: ${path.relative(ROOT, OUTPUT)}`);
console.log(`   ${imports.length} files → ${totalLines} lines → ${bundleSizeKB} KB`);
