#!/usr/bin/env node
/**
 * build-css.js — CSS Bundle Builder
 *
 * Concatenates the modular CSS files (assets/css/**) into a single
 * production bundle: assets/css/main.bundled.css
 *
 * The cascade order below is the source of truth for load order
 * (it replaces the old assets/css/main.css @import manifest, which was
 * removed). Order matters — do NOT alphabetise. Append new modules in
 * the correct layer: base -> layout -> components -> features ->
 * utilities -> themes. (Page-specific files under pages/ are loaded
 * directly by their own pages and are intentionally NOT bundled.)
 *
 * Usage:   npm run build:css   (or: node tools/build-css.js)
 *
 * The modular source files remain the source of truth; the bundle is a
 * build artifact. CI re-runs this on every push so the two never drift.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CSS_DIR = path.join(ROOT, 'assets', 'css');
const OUTPUT = path.join(CSS_DIR, 'main.bundled.css');

// --- Cascade order (load order = source of truth) ---
const MODULES = [
  // 1. Base — tokens and resets first
  'base/variables.css',
  'base/reset.css',
  'base/typography.css',
  'base/animations.css',
  // 2. Layout — structural shells
  'layout/header.css',
  'layout/footer.css',
  'layout/sections.css',
  // 3. Components — reusable UI atoms
  'components/buttons.css',
  'components/forms.css',
  'components/badges.css',
  'components/cards.css',
  'components/modals.css',
  'components/review-modal.css',
  // 4. Features — page sections
  'features/hero.css',
  'features/services.css',
  'features/gallery.css',
  'features/contact.css',
  'features/products.css',
  'features/testimonials.css',
  'features/why-choose.css',
  'features/quote-calculator.css',
  'features/stationery-search.css',
  'features/bulk-order.css',
  'features/order-status.css',
  // 5. Utilities — helpers and interactive layer
  'utilities/trust-counters.css',
  'utilities/interactive.css',
  'utilities/view-transitions.css',
  'utilities/responsive-mobile.css',
  // 6. Themes — must come last to override cleanly
  'themes/dark.css',
];

const timestamp = new Date().toISOString().replace('T', ' ').split('.')[0];
const parts = [
  `/* ================================================================`,
  `   main.bundled.css — Auto-generated by tools/build-css.js`,
  `   Generated: ${timestamp}`,
  `   Source modules: ${MODULES.length} (cascade order)`,
  ``,
  `   DO NOT EDIT THIS FILE DIRECTLY.`,
  `   Edit the individual module files under assets/css/ instead,`,
  `   then re-run: npm run build:css`,
  `   ================================================================ */`,
  ``,
];

let totalLines = 0;

for (const rel of MODULES) {
  const filePath = path.join(CSS_DIR, rel);
  if (!fs.existsSync(filePath)) {
    console.error(`  ✗ MISSING: assets/css/${rel}`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  totalLines += content.split('\n').length;

  parts.push(`/* --- assets/css/${rel} --- */`);
  parts.push(content.trim());
  parts.push('');

  console.log(`  ✓ assets/css/${rel}`);
}

const bundle = parts.join('\n');
fs.writeFileSync(OUTPUT, bundle, 'utf8');

const bundleSizeKB = (Buffer.byteLength(bundle, 'utf8') / 1024).toFixed(1);
console.log(`\n✅ Bundle written: ${path.relative(ROOT, OUTPUT)}`);
console.log(`   ${MODULES.length} modules → ${totalLines} lines → ${bundleSizeKB} KB`);
